// Standard ABO/Rh red-cell compatibility. Same rules every blood bank teaches; the final match is always done by the hospital.
export const GROUPS = ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'] as const;
export type Group = (typeof GROUPS)[number];
export const slugOf = (g: Group) => g.replace('+', '-positive').replace(/-$/, '-negative').toLowerCase();
export const fromSlug = (s: string) => GROUPS.find((g) => slugOf(g) === s);
export const RECEIVE_FROM: Record<Group, Group[]> = {
  'O-': ['O-'], 'O+': ['O+', 'O-'], 'A-': ['A-', 'O-'], 'A+': ['A+', 'A-', 'O+', 'O-'],
  'B-': ['B-', 'O-'], 'B+': ['B+', 'B-', 'O+', 'O-'], 'AB-': ['AB-', 'A-', 'B-', 'O-'], 'AB+': ['AB+', 'AB-', 'A+', 'A-', 'B+', 'B-', 'O+', 'O-'],
};
export const DONATE_TO = (g: Group): Group[] => GROUPS.filter((x) => RECEIVE_FROM[x].includes(g));

// 64 districts (key, Bangla name, division). Used for blood donor organisations.
export const DISTRICTS: Record<string, { bn: string; division: string }> = {
  dhaka: { bn: 'ঢাকা', division: 'ঢাকা বিভাগ' },
  gazipur: { bn: 'গাজীপুর', division: 'ঢাকা বিভাগ' },
  narayanganj: { bn: 'নারায়ণগঞ্জ', division: 'ঢাকা বিভাগ' },
  narsingdi: { bn: 'নরসিংদী', division: 'ঢাকা বিভাগ' },
  manikganj: { bn: 'মানিকগঞ্জ', division: 'ঢাকা বিভাগ' },
  munshiganj: { bn: 'মুন্সীগঞ্জ', division: 'ঢাকা বিভাগ' },
  kishoreganj: { bn: 'কিশোরগঞ্জ', division: 'ঢাকা বিভাগ' },
  tangail: { bn: 'টাঙ্গাইল', division: 'ঢাকা বিভাগ' },
  faridpur: { bn: 'ফরিদপুর', division: 'ঢাকা বিভাগ' },
  gopalganj: { bn: 'গোপালগঞ্জ', division: 'ঢাকা বিভাগ' },
  madaripur: { bn: 'মাদারীপুর', division: 'ঢাকা বিভাগ' },
  rajbari: { bn: 'রাজবাড়ী', division: 'ঢাকা বিভাগ' },
  shariatpur: { bn: 'শরীয়তপুর', division: 'ঢাকা বিভাগ' },
  chattogram: { bn: 'চট্টগ্রাম', division: 'চট্টগ্রাম বিভাগ' },
  coxsbazar: { bn: 'কক্সবাজার', division: 'চট্টগ্রাম বিভাগ' },
  cumilla: { bn: 'কুমিল্লা', division: 'চট্টগ্রাম বিভাগ' },
  brahmanbaria: { bn: 'ব্রাহ্মণবাড়িয়া', division: 'চট্টগ্রাম বিভাগ' },
  chandpur: { bn: 'চাঁদপুর', division: 'চট্টগ্রাম বিভাগ' },
  feni: { bn: 'ফেনী', division: 'চট্টগ্রাম বিভাগ' },
  lakshmipur: { bn: 'লক্ষ্মীপুর', division: 'চট্টগ্রাম বিভাগ' },
  noakhali: { bn: 'নোয়াখালী', division: 'চট্টগ্রাম বিভাগ' },
  khagrachhari: { bn: 'খাগড়াছড়ি', division: 'চট্টগ্রাম বিভাগ' },
  rangamati: { bn: 'রাঙামাটি', division: 'চট্টগ্রাম বিভাগ' },
  bandarban: { bn: 'বান্দরবান', division: 'চট্টগ্রাম বিভাগ' },
  sylhet: { bn: 'সিলেট', division: 'সিলেট বিভাগ' },
  moulvibazar: { bn: 'মৌলভীবাজার', division: 'সিলেট বিভাগ' },
  habiganj: { bn: 'হবিগঞ্জ', division: 'সিলেট বিভাগ' },
  sunamganj: { bn: 'সুনামগঞ্জ', division: 'সিলেট বিভাগ' },
  rajshahi: { bn: 'রাজশাহী', division: 'রাজশাহী বিভাগ' },
  bogura: { bn: 'বগুড়া', division: 'রাজশাহী বিভাগ' },
  joypurhat: { bn: 'জয়পুরহাট', division: 'রাজশাহী বিভাগ' },
  naogaon: { bn: 'নওগাঁ', division: 'রাজশাহী বিভাগ' },
  natore: { bn: 'নাটোর', division: 'রাজশাহী বিভাগ' },
  chapainawabganj: { bn: 'চাঁপাইনবাবগঞ্জ', division: 'রাজশাহী বিভাগ' },
  pabna: { bn: 'পাবনা', division: 'রাজশাহী বিভাগ' },
  sirajganj: { bn: 'সিরাজগঞ্জ', division: 'রাজশাহী বিভাগ' },
  khulna: { bn: 'খুলনা', division: 'খুলনা বিভাগ' },
  bagerhat: { bn: 'বাগেরহাট', division: 'খুলনা বিভাগ' },
  chuadanga: { bn: 'চুয়াডাঙ্গা', division: 'খুলনা বিভাগ' },
  jashore: { bn: 'যশোর', division: 'খুলনা বিভাগ' },
  jhenaidah: { bn: 'ঝিনাইদহ', division: 'খুলনা বিভাগ' },
  kushtia: { bn: 'কুষ্টিয়া', division: 'খুলনা বিভাগ' },
  magura: { bn: 'মাগুরা', division: 'খুলনা বিভাগ' },
  meherpur: { bn: 'মেহেরপুর', division: 'খুলনা বিভাগ' },
  narail: { bn: 'নড়াইল', division: 'খুলনা বিভাগ' },
  satkhira: { bn: 'সাতক্ষীরা', division: 'খুলনা বিভাগ' },
  barishal: { bn: 'বরিশাল', division: 'বরিশাল বিভাগ' },
  barguna: { bn: 'বরগুনা', division: 'বরিশাল বিভাগ' },
  bhola: { bn: 'ভোলা', division: 'বরিশাল বিভাগ' },
  jhalokati: { bn: 'ঝালকাঠি', division: 'বরিশাল বিভাগ' },
  patuakhali: { bn: 'পটুয়াখালী', division: 'বরিশাল বিভাগ' },
  pirojpur: { bn: 'পিরোজপুর', division: 'বরিশাল বিভাগ' },
  rangpur: { bn: 'রংপুর', division: 'রংপুর বিভাগ' },
  dinajpur: { bn: 'দিনাজপুর', division: 'রংপুর বিভাগ' },
  gaibandha: { bn: 'গাইবান্ধা', division: 'রংপুর বিভাগ' },
  kurigram: { bn: 'কুড়িগ্রাম', division: 'রংপুর বিভাগ' },
  lalmonirhat: { bn: 'লালমনিরহাট', division: 'রংপুর বিভাগ' },
  nilphamari: { bn: 'নীলফামারী', division: 'রংপুর বিভাগ' },
  panchagarh: { bn: 'পঞ্চগড়', division: 'রংপুর বিভাগ' },
  thakurgaon: { bn: 'ঠাকুরগাঁও', division: 'রংপুর বিভাগ' },
  mymensingh: { bn: 'ময়মনসিংহ', division: 'ময়মনসিংহ বিভাগ' },
  jamalpur: { bn: 'জামালপুর', division: 'ময়মনসিংহ বিভাগ' },
  netrokona: { bn: 'নেত্রকোণা', division: 'ময়মনসিংহ বিভাগ' },
  sherpur: { bn: 'শেরপুর', division: 'ময়মনসিংহ বিভাগ' },
};
export const districtBn = (k: string) => DISTRICTS[k]?.bn ?? k;
