title: "World Bank to provide $300m for emergency food security support in Bangladesh"
source: "The Business Standard"
url: https://www.tbsnews.net/economy/world-bank-provide-300m-emergency-food-security-support-bangladesh-1563576
date: 2026-10-05
cat: অর্থনীতি
